services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306

  api:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - database