version: "3.8"

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - mynetwork

  api:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}  # Usa a variável PORT do Railway
    ports:
      - "${PORT}:${PORT}"  # Mapeia a porta automaticamente configurada pelo Railway
    depends_on:
      - database
    networks:
      - mynetwork
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh database:3306 -- java -jar /app.jar"]

networks:
  mynetwork:
    driver: bridge
