services:
  database:
      image: mysql:latest
      environment:
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      ports:
        - 3306:3306
